-- medical_claim
-- This is the model the Tuva package references as ref('medical_claim').
-- Tuva's own input_layer__medical_claim is select * from ref('medical_claim').
-- Placed in models/input_layer/ but the MODEL NAME must be medical_claim.
-- Thin contract model. One row per final-adjudicated professional claim line.
-- Selects the full Tuva input_layer medical_claim contract in exact order
-- (148 columns). Populated columns come from int_medical_claim; columns that do
-- not apply to a professional 837P/835 source (institutional fields, ICD
-- procedure and present-on-admission arrays, fields not present in the EDI) are
-- explicit typed NULLs so the contract's expect_column_to_exist checks pass.
-- data_source is a literal identifying this connector and is part of the
-- primary key (claim_id, claim_line_number, data_source).

with medical_claim as (
    select * from {{ ref('int_medical_claim') }}
)

select
    claim_id,
    claim_line_number,
    claim_type,
    person_id,
    member_id,
    payer,
    cast(null as varchar) as plan,
    claim_start_date,
    claim_end_date,
    claim_line_start_date,
    claim_line_end_date,
    cast(null as date) as admission_date,
    cast(null as date) as discharge_date,
    cast(null as varchar) as admit_source_code,
    cast(null as varchar) as admit_type_code,
    cast(null as varchar) as discharge_disposition_code,
    place_of_service_code,
    cast(null as varchar) as bill_type_code,
    cast(null as varchar) as drg_code_type,
    cast(null as varchar) as drg_code,
    cast(null as varchar) as revenue_center_code,
    service_unit_quantity,
    hcpcs_code,
    hcpcs_modifier_1,
    hcpcs_modifier_2,
    hcpcs_modifier_3,
    hcpcs_modifier_4,
    cast(null as varchar) as hcpcs_modifier_5,
    rendering_npi,
    cast(null as varchar) as rendering_tin,
    billing_npi,
    cast(null as varchar) as billing_tin,
    cast(null as varchar) as facility_npi,
    cast(null as date) as paid_date,
    paid_amount,
    allowed_amount,
    charge_amount,
    coinsurance_amount,
    copayment_amount,
    deductible_amount,
    cast(null as float) as total_cost_amount,
    diagnosis_code_type,
    diagnosis_code_1,
    diagnosis_code_2,
    diagnosis_code_3,
    diagnosis_code_4,
    diagnosis_code_5,
    diagnosis_code_6,
    diagnosis_code_7,
    diagnosis_code_8,
    diagnosis_code_9,
    diagnosis_code_10,
    diagnosis_code_11,
    diagnosis_code_12,
    diagnosis_code_13,
    diagnosis_code_14,
    diagnosis_code_15,
    diagnosis_code_16,
    diagnosis_code_17,
    diagnosis_code_18,
    diagnosis_code_19,
    diagnosis_code_20,
    diagnosis_code_21,
    diagnosis_code_22,
    diagnosis_code_23,
    diagnosis_code_24,
    diagnosis_code_25,
    cast(null as varchar) as diagnosis_poa_1,
    cast(null as varchar) as diagnosis_poa_2,
    cast(null as varchar) as diagnosis_poa_3,
    cast(null as varchar) as diagnosis_poa_4,
    cast(null as varchar) as diagnosis_poa_5,
    cast(null as varchar) as diagnosis_poa_6,
    cast(null as varchar) as diagnosis_poa_7,
    cast(null as varchar) as diagnosis_poa_8,
    cast(null as varchar) as diagnosis_poa_9,
    cast(null as varchar) as diagnosis_poa_10,
    cast(null as varchar) as diagnosis_poa_11,
    cast(null as varchar) as diagnosis_poa_12,
    cast(null as varchar) as diagnosis_poa_13,
    cast(null as varchar) as diagnosis_poa_14,
    cast(null as varchar) as diagnosis_poa_15,
    cast(null as varchar) as diagnosis_poa_16,
    cast(null as varchar) as diagnosis_poa_17,
    cast(null as varchar) as diagnosis_poa_18,
    cast(null as varchar) as diagnosis_poa_19,
    cast(null as varchar) as diagnosis_poa_20,
    cast(null as varchar) as diagnosis_poa_21,
    cast(null as varchar) as diagnosis_poa_22,
    cast(null as varchar) as diagnosis_poa_23,
    cast(null as varchar) as diagnosis_poa_24,
    cast(null as varchar) as diagnosis_poa_25,
    cast(null as varchar) as procedure_code_type,
    cast(null as varchar) as procedure_code_1,
    cast(null as varchar) as procedure_code_2,
    cast(null as varchar) as procedure_code_3,
    cast(null as varchar) as procedure_code_4,
    cast(null as varchar) as procedure_code_5,
    cast(null as varchar) as procedure_code_6,
    cast(null as varchar) as procedure_code_7,
    cast(null as varchar) as procedure_code_8,
    cast(null as varchar) as procedure_code_9,
    cast(null as varchar) as procedure_code_10,
    cast(null as varchar) as procedure_code_11,
    cast(null as varchar) as procedure_code_12,
    cast(null as varchar) as procedure_code_13,
    cast(null as varchar) as procedure_code_14,
    cast(null as varchar) as procedure_code_15,
    cast(null as varchar) as procedure_code_16,
    cast(null as varchar) as procedure_code_17,
    cast(null as varchar) as procedure_code_18,
    cast(null as varchar) as procedure_code_19,
    cast(null as varchar) as procedure_code_20,
    cast(null as varchar) as procedure_code_21,
    cast(null as varchar) as procedure_code_22,
    cast(null as varchar) as procedure_code_23,
    cast(null as varchar) as procedure_code_24,
    cast(null as varchar) as procedure_code_25,
    cast(null as date) as procedure_date_1,
    cast(null as date) as procedure_date_2,
    cast(null as date) as procedure_date_3,
    cast(null as date) as procedure_date_4,
    cast(null as date) as procedure_date_5,
    cast(null as date) as procedure_date_6,
    cast(null as date) as procedure_date_7,
    cast(null as date) as procedure_date_8,
    cast(null as date) as procedure_date_9,
    cast(null as date) as procedure_date_10,
    cast(null as date) as procedure_date_11,
    cast(null as date) as procedure_date_12,
    cast(null as date) as procedure_date_13,
    cast(null as date) as procedure_date_14,
    cast(null as date) as procedure_date_15,
    cast(null as date) as procedure_date_16,
    cast(null as date) as procedure_date_17,
    cast(null as date) as procedure_date_18,
    cast(null as date) as procedure_date_19,
    cast(null as date) as procedure_date_20,
    cast(null as date) as procedure_date_21,
    cast(null as date) as procedure_date_22,
    cast(null as date) as procedure_date_23,
    cast(null as date) as procedure_date_24,
    cast(null as date) as procedure_date_25,
    cast(null as boolean) as in_network_flag,
    cast(null as varchar) as file_name,
    cast(null as date) as file_date,
    cast(null as timestamp) as ingest_datetime,
    '{{ var('data_source', 'riverbend_837p') }}' as data_source
from medical_claim
